[package]
name = "alternate-protocol-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
insta = { version = "1.41.1", features = ["glob"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }